[Desktop Entry]
Type=X-GNOME-Metatheme
Name=oomox-light-mode-v1
Comment=A partially sexual act; when a female (of any species; mostly humanoids) rubs the ears/lobes of a male Ferengi, creating sensual emotions and chemical reactions in the male (and sometimes in the female).
Encoding=UTF-8

[X-GNOME-Metatheme]
Name=oomox-light-mode-v1
GtkTheme=oomox-light-mode-v1
IconTheme=oomox-light-mode-v1
MetacityTheme=oomox-light-mode-v1
