# Shell variables
# Generated by 'wal'
wallpaper="/home/user/.config/dark-mode/pywal-sample/pywal-sample.jpg"

# Special
background='#0E0B12'
foreground='#91bab4'
cursor='#91bab4'

# Colors
color0='#0E0B12'
color1='#81002c'
color2='#7a0079'
color3='#007972'
color4='#a80032'
color5='#c30045'
color6='#fe075d'
color7='#91bab4'
color8='#65827d'
color9='#81002c'
color10='#7a0079'
color11='#007972'
color12='#a80032'
color13='#c30045'
color14='#fe075d'
color15='#91bab4'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
