--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/user/.config/dark-mode/pywal-sample/pywal-sample.jpg"

-- Special
background="#0E0B12"
foreground="#91bab4"
cursor="#91bab4"

-- Colors
color0="#0E0B12"
color1="#81002c"
color2="#7a0079"
color3="#007972"
color4="#a80032"
color5="#c30045"
color6="#fe075d"
color7="#91bab4"
color8="#65827d"
color9="#81002c"
color10="#7a0079"
color11="#007972"
color12="#a80032"
color13="#c30045"
color14="#fe075d"
color15="#91bab4"
