# Shell variables
# Generated by 'wal'
wallpaper="/home/user/.config/light-mode/wallpaper/wallpaper.jpg"

# Special
background='#edeff8'
foreground='#13111C'
cursor='#13111C'

# Colors
color0='#edeff8'
color1='#1800a9'
color2='#000aba'
color3='#0046db'
color4='#0020ff'
color5='#671aff'
color6='#3a74ff'
color7='#13111C'
color8='#545a80'
color9='#1800a9'
color10='#000aba'
color11='#0046db'
color12='#0020ff'
color13='#671aff'
color14='#3a74ff'
color15='#13111C'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
